### ISSUE TITLE
03_data_analysis_by_gen_ai のGenieスペース作成の説明

### ISSUE THREAD

**Issue by yuharucan** [skotani-db/openhack2024#10]
ワークスペースにてGenieプレビューをオンにしてリロードを実施する説明の追加、およびタイトル部分の綴り間違い。
![03_data_analysis_by_gen_ai_Genie_exp](https://github.com/user-attachments/assets/1df36674-5ba7-43e8-8ca8-8a645c0c6e5e)

**Comment by manabian-** [comment]
Genei の誤字は修正

https://github.com/skotani-db/openhack2024/commit/69ec248647fd6ff5584507f032af4925586844ee

**Comment by manabian-** [comment]
> ワークスペースにてGenieプレビューをオンにしてリロードを実施する説明の追加

上記のついては、初回のみ表示されるため追記するかを要検討。

**Comment by yuharucan** [comment]
"※"などつけて注意書きとして、"利用初回時には"をつけて記載するのは如何でしょうか。

**Comment by manabian-** [comment]
Genie スペース作成時に項目が出ないことを確認できたため、その手順の注意書きとして追記しました。

https://github.com/skotani-db/openhack2024/commit/c517e079788f48d949b8256f31f0060c136d7280
