### ISSUE TITLE
03_data_analysis_by_gen_ai の Q4について

### ISSUE THREAD

**Issue by yuharucan** [skotani-db/openhack2024#11]
"2. Trusted AssetsにおけるAdd trusted assetを選択" とあるが、画面では"SQL Functions"となっている。
![03_data_analysis_by_gen_ai_Q4](https://github.com/user-attachments/assets/7b4793ad-fec6-41a0-81d6-6fb5843f86fa)

**Comment by manabian-** [comment]
対応済み
