### ISSUE TITLE
"04_aibi_contest_answer"のCell6の"-- ケースのレビューテーブル作成"のカタログ、スキーマについて

### ISSUE THREAD

**Issue by yuharucan** [skotani-db/openhack2024#15]
View定義のFROM句でteam_masterカタログから取得する定義となっておりますが、
各個別のカタログ、スキーマからが正しいでしょうか。

FROM　team_master.`03_data_analysis_by_gen_ai_for_ktn`
.`case`
LIMIT 100;
"""

**Comment by skotani-db** [comment]
個別のカタログ、スキーマを埋め込む形に変更しました
<img width="679" alt="スクリーンショット 2024-08-26 17 12 31" src="https://github.com/user-attachments/assets/c0da8850-189c-4743-b0f1-d67ae5040b20">
