### ISSUE TITLE
DLT - Serverless を利用する形に notebook 内の説明を修正

### ISSUE THREAD

**Issue by matakeda1** [skotani-db/openhack2024#2]
今回はサーバーレスを主張したいと DBX サンから依頼があるので、こちらもサーバーレスにしてみてはどうでしょう。
 
![image](https://github.com/user-attachments/assets/f46577c1-5a94-4815-9a5e-7e8b30d5b6e3)

**Comment by manabian-** [comment]
下記のコミットで対応

https://github.com/skotani-db/openhack2024/commit/e44406f757ebdd28bfa2409caa549fc2c1e85f3d

**Comment by matakeda1** [comment]
[like]  Masaki Takeda (DATA PLATFORM) reacted to your message:
________________________________
