### ISSUE TITLE
テーブル名の補足

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#20]
同じような操作が続くため、現在対象にしているテーブルを補足するとわかりやすいと感じました。

e.g.
**product2の**ブロンズテーブルから主キー（`Id`）ごとに`_ingest_timestamp`列の最大日を抽出したサブセットを作成

https://github.com/skotani-db/openhack2024/blob/20d106aee5400adcc59ea904e86441d99827c8e6/content/01_medallion_architecture.py#L317

**Comment by manabian-** [comment]
対応済み
