### ISSUE TITLE
題材にするデータの補足説明

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#21]
取り込みを行うデータセットに対する説明と(e.g. オープンデータの場合URLを記載するなど)、各CSVファイルがどんなエンティティなのか簡単な説明が欲しいと感じました。

https://github.com/skotani-db/openhack2024/blob/1dfbd8e2c4379d7714c68ce56529532e4c5001a2/content/01_medallion_architecture.py#L105

**Comment by manabian-** [comment]
対応済み
