### ISSUE TITLE
各課題の所要時間の目安

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#23]
各チームでChallengeをスキップするかどうかの判断のため、各課題の所要時間の目安があると良いと感じました。
(当日タイムテーブルとの突合せが必要)

**Comment by manabian-** [comment]
下記のコミットにて 1 ～ 3 のノートブックで対応。 

- https://github.com/skotani-db/openhack2024/commit/769ac1bd4746702741b8a0b02b2308a8afbb35ed

**Comment by manabian-** [comment]
4 のノートブックの対については、下記の issue を新規で作成。こちらは一旦クローズとする。

04_aibi_contest_answer に 標準時間を記述 #35
