### ISSUE TITLE
サーバレスでAutoLoaderのstreamを流し続けた場合にどうなるか

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#25]
仕様上の挙動が理解できていないのですが、サーバレスでstreamを流し続けた場合コンピューティングは起動し続けるのでしょうか？
もしかすると気になる参加者もいるかもしれないと感じました。

https://github.com/skotani-db/openhack2024/blob/1dfbd8e2c4379d7714c68ce56529532e4c5001a2/content/01_medallion_architecture.py#L854

**Comment by manabian-** [comment]
現時点でドキュメントにてコストの計算方法を提示できず明確な回答ができない可能性が高いため、コンテンツへの反映は難しそうです。

もし質問がきた場合には、有識者を探して回答することになりそうです。

**Comment by manabian-** [comment]
> サーバレスでstreamを流し続けた場合コンピューティングは起動し続けるのでしょうか？

私の推測ではありますが、上記についてはノートブックに サーバーレスクラスターがアタッチされたままとなるため、コストがかかり続ける認識です。

一度クラスターをアタッチ後に、何も操作をしない場合には 1 時間後にで自動でデタッチされる動作を１度確認できました。

**Comment by rsk800** [comment]
コメントありがとうございます。
ここまで気が回る参加者がいるかどうかは分かりませんが、もし質問が出た場合は下記で対応しましょう。
> 有識者を探して回答
