### ISSUE TITLE
OpenHackで選択すべきパイプラインモード

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#26]
このOpenHackではどちらを選択するかのガイドがあると良いと感じます。

https://github.com/skotani-db/openhack2024/blob/19eadf5e8b81ccb395ee4ddf3abb768a3eb718fe/contents_with_answer/02_data_engineering.py#L72

**Comment by manabian-** [comment]
Trigger を選ぶ理由を追記しました。

> 本手順ではファイルの取り込みを1回のみ行うため、`Trigger`を選択しています。

![image](https://github.com/user-attachments/assets/3a7d118e-1483-4fe9-97de-d70e75f02512)
