### ISSUE TITLE
DLT Destination

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#27]
このOpenHackではカタログを選択すべきか、選択する場合どのカタログを選択するのかのガイドがあると良いと感じます。

https://github.com/skotani-db/openhack2024/blob/19eadf5e8b81ccb395ee4ddf3abb768a3eb718fe/contents_with_answer/02_data_engineering.py#L79

**Comment by manabian-** [comment]
項目を表示するコードを書き忘れていたため、追記しました。

> 下記のセルでCatalogとTarget schemaの隣に表示されているカタログ名とスキーマ名を指定します。

![image](https://github.com/user-attachments/assets/7ebfe370-c5d7-4a9d-8cb4-469d2a65fdb0)
