### ISSUE TITLE
DLT Key-Value configurations

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#28]
AdvancedセクションのAdd ConfigurationでKey/Valueを設定？

https://github.com/skotani-db/openhack2024/blob/19eadf5e8b81ccb395ee4ddf3abb768a3eb718fe/contents_with_answer/02_data_engineering.py#L85

**Comment by manabian-** [comment]
領域の項目名（Advanced）を追記しました。

> AdvancedにおけるConfigurationeにてAdd configurationを選択して下記の 2 つを設定します。

![image](https://github.com/user-attachments/assets/ddbc2b8c-3453-40c6-b087-a5a6e64c2139)

![image](https://github.com/user-attachments/assets/c910e7be-416f-4325-9610-ae085c0774e9)
