### ISSUE TITLE
DLT - アラート機能も体験頂く形にしてはどうでしょう

### ISSUE THREAD

**Issue by matakeda1** [skotani-db/openhack2024#3]
通知も入れてもよいかなと思いました。よくジョブの成功失敗を通知する仕組みについては、質問される印象があります。

![image](https://github.com/user-attachments/assets/9540567f-8aa6-4221-9444-129a6cf12213)

**Comment by manabian-** [comment]
下記で対応

https://github.com/skotani-db/openhack2024/commit/aad75c1b4be5029c7a03960a6863dd028f7e6823

**Comment by matakeda1** [comment]
[like]  Masaki Takeda (DATA PLATFORM) reacted to your message:
________________________________
