### ISSUE TITLE
Genieにサンプルクエリを追加しても値がnullのまま

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#30]
![image](https://github.com/user-attachments/assets/473ed6f4-84b8-452c-ad2d-500f9452cc36)

https://github.com/skotani-db/openhack2024/blob/19eadf5e8b81ccb395ee4ddf3abb768a3eb718fe/contents_with_answer/03_data_analysis_by_gen_ai.py#L158

**Comment by manabian-** [comment]
Genie くんは時々このような動作をしてしまうときがあるようで、少し待つと想定通りに回答してくれるときがあります。

トレーニング時になったら困りますね。

**Comment by manabian-** [comment]
質問文を変えたら、でてきました。回答が来ない場合には、下記のように質問するように追記します。

> Show me the sales amount by order date based on Example SQL Queries.

![image](https://github.com/user-attachments/assets/689285e6-3c7d-4913-b732-93cf191153bf)
