### ISSUE TITLE
Pipelineとは

### ISSUE THREAD

**Issue by rsk800** [skotani-db/openhack2024#31]
直前にDLTの課題があるため、初見ではDLTのpipelineと関連があのではと思いました。
この文脈では、Sales Force Automation社のsales pipelineを取得するクエリだという補足があっても良いと感じました。

https://github.com/skotani-db/openhack2024/blob/19eadf5e8b81ccb395ee4ddf3abb768a3eb718fe/contents_with_answer/03_data_analysis_by_gen_ai.py#L216

**Comment by manabian-** [comment]
ご認識の通り、ここの pipeline は 営業活動におけるパイプラインです。

![image](https://github.com/user-attachments/assets/c53b1bbb-31ae-415c-9457-5348e7b5924a)

引用元：https://www.salesforce.com/jp/blog/jp-pipeline-management/

参考リンクを追記しました。

![image](https://github.com/user-attachments/assets/1b145da3-e166-4ee6-a343-8969cd87b855)

**Comment by manabian-** [comment]
追記もしました。

> この質問におけるpipelineは、データエンジニアリング（Delta live Tables）のパイプラインではなく、営業活動に関連するパイプラインを指します。

![image](https://github.com/user-attachments/assets/05896d8a-ebf9-4ba7-931b-80ba0ee2ed3a)
