### ISSUE TITLE
01_medallion_architectureのCell66にてSQLSTATE: 42704

### ISSUE THREAD

**Issue by yuharucan** [skotani-db/openhack2024#7]
01_medallion_architecture の Cell66 にて SQLSTATE: 42704 が発生します。

![01_medallion_architecture_cell65_error](https://github.com/user-attachments/assets/d082aaf4-1ecb-4412-bc25-cdc63171b78c)

**Comment by manabian-** [comment]
PySpark にて select メソッドと withcolumn メソッドを続けて利用するとスキーマが喪失する事象を確認。通常のクラスターでは実施できていたのでサーバーレスのバグの可能性あり。

![image](https://github.com/user-attachments/assets/dbebbb1d-1281-4526-87f5-3cd11073cdd9)

**Comment by manabian-** [comment]
分割して記述すことで動作したため、本対応を実施することとする。

![image](https://github.com/user-attachments/assets/b9f1b283-ae6a-49ed-aaf0-ac87c64e623e)

**Comment by manabian-** [comment]
対応済み
