### ISSUE TITLE
02_data_engineering の Cell 10の場所

### ISSUE THREAD

**Issue by yuharucan** [skotani-db/openhack2024#8]
Cell 10上部のMakdownでは"上記のセルに記載されている pipeline_name を使用することをおすすめします。"と表記されていますが、
”上記"ではなく"下記"かなと。

![02_data_engineering_cell10](https://github.com/user-attachments/assets/6cd36a32-2a29-41c3-b59f-747d93fbdbab)

**Comment by manabian-** [comment]
対応済み
